# coding: utf-8

"""
    partner-api

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import tinker_partner_api_wrapper
from tinker_partner_api_wrapper.rest import ApiException
from tinker_partner_api_wrapper.apis.partner_booking_api import PartnerBookingApi


class TestPartnerBookingApi(unittest.TestCase):
    """ PartnerBookingApi unit test stubs """

    def setUp(self):
        self.api = tinker_partner_api_wrapper.apis.partner_booking_api.PartnerBookingApi()

    def tearDown(self):
        pass

    def test_partner_booking_airports(self):
        """
        Test case for partner_booking_airports

        Retrieves a list of all tinker-activated airports
        """
        pass

    def test_partner_booking_confirm(self):
        """
        Test case for partner_booking_confirm

        Confirm a previously created set of price quotes
        """
        pass

    def test_partner_booking_locations(self):
        """
        Test case for partner_booking_locations

        Retrieves a geoloc-id for a given location
        """
        pass

    def test_partner_booking_request_from_airport_booking(self):
        """
        Test case for partner_booking_request_from_airport_booking

        Request a price quote for a trip starting FROM an airport.
        """
        pass

    def test_partner_booking_request_to_airport_booking(self):
        """
        Test case for partner_booking_request_to_airport_booking

        Request a price quote for a trip TO an airport
        """
        pass


if __name__ == '__main__':
    unittest.main()
